# default configuration
baseURL = "http://localhost:1313/"
title = "Promacanthus"
theme = "timer-hugo"
languageCode = "zh"
hasCJKLanguage = true

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "zh"

summaryLength = "10"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Code highlight
pygmentsUseClasses = false
pygmentCodeFences = true

# Enable google analytics by uncomment this
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

# css plugins
# [[params.plugins.css]]
# URL = "plugins/bootstrap/bootstrap.min.css"
# [[params.plugins.css]]
# URL = "plugins/slick/slick.css"
# [[params.plugins.css]]
# URL = "plugins/themify-icons/themify-icons.css"


# js plugin
# [[params.plugins.js]]
# URL = "plugins/jQuery/jquery.min.js"
# [[params.plugins.js]]
# URL = "plugins/bootstrap/bootstrap.min.js"
# [[params.plugins.js]]
# URL = "plugins/slick/slick.min.js"
# [[params.plugins.js]]
# URL = "plugins/shuffle/shuffle.min.js"


# Main menu
[[menu.main]]
# name = "主页"
# URL = "/"
# weight = 1

[[menu.main]]
name = "关于"
URL = "about"
weight = 1

[[menu.main]]
name = "参考指南"
identifier = "guide"
weight = 2

[[menu.main]]
name = "填坑记录"
identifier = "experience"
weight = 3

[[menu.main]]
parent = "guide"
name = "云原生"
URL = "cloudnative"
weight = 1

[[menu.main]]
parent = "guide"
name = "微服务"
URL = "microservice"
weight = 2

[[menu.main]]
parent = "guide"
name = "Go语言"
URL = "Golang"
weight = 3

[[menu.main]]
parent = "guide"
name = "集成开发环境"
URL = "ide"
weight = 4

[[menu.main]]
parent = "guide"
name = "常用开发框架"
URL = "framework"
weight = 5

[[menu.main]]
parent = "guide"
name = "常用工具"
URL = "tool"
weight = 6

[[menu.main]]
parent = "experience"
name = "Golang"
URL = "experience/Golang"
weight = 1

[[menu.main]]
parent = "experience"
name = "Dokcer"
URL = "experience/Docker"
weight = 2

[[menu.main]]
parent = "experience"
name = "Kubernetes"
URL = "experience/Kubernetes"
weight = 3

[[menu.main]]
parent = "experience"
name = "MySQL"
URL = "experience/MySQL"
weight = 4

[[menu.main]]
parent = "experience"
name = "HTTP"
URL = "experience/HTTP"
weight = 5

[[menu.main]]
parent = "experience"
name = "Traefik"
URL = "experience/Traefik"
weight = 6

# default parameters
[params]
home = "主页"
# logo = "images/logo.png"
# theme color
theme_color = "#41228e"
# contact info
# phone = "+880 2544 658 256"
# email = "promacanthus@gmail.com"
# address = "125/A, CA Commercial Area, California, USA"
# meta description
author = "Bowen Zhu"
# description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"


# contact
[params.contact]
# enable = true
form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.socialIcon]]
url = "https://github.com/Promacanthus"
icon = "ion-social-github"


[params.widgets]
categories = true
tags = true
search = true

# Banner Section
[params.banner]
enable  = true

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT ME"