# Project information
site_name: Golang Guide
site_description: Go language full stack development guide
site_author: bowen zhu
site_url: https://promacanthus.github.io/Golang-Guide/
site_favicon: favicon.ico

# Repository
repo_name: promacanthus/Golang-Guide
repo_url: https://github.com/Promacanthus/Golang-Guide
edit_uri: "blob/gh-pages/"

# Configuration
theme:
  name: 'material'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Promacanthus'

# 404 page
static_templates:
  - 404.html

# Analytics
google_analytics: ['UA-151903408-1', 'mkdocs.org']

# Don't include MkDocs' JavaScript
include_search_page: false
search_index_only: true

# Customization
extra:
  social:
    - type: github
      link: https://github.com/Promacanthus/Golang-Guide
