# Project information
site_name: Golang Guide
site_description: Go language full stack development guide
site_author: bowen zhu
site_url: https://promacanthus.github.io/Golang-Guide/

# Repository
repo_name: promacanthus/Golang-Guide
repo_url: https://github.com/Promacanthus/Golang-Guide

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'Cyan'
    accent: 'Cyan'
  logo: 
    icon: 'code'
  language: 'zh'
  feature:
    tabs: true
  favicon: https://go.dev/favicon.ico

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Promacanthus'

# Analytics
google_analytics: 
  - 'UA-151903408-1'
  - 'auto'

# Customization
extra:
  social:
    - type: github
      link: https://github.com/Promacanthus/Golang-Guide
  # disqus: disqus_VS56K9XVsG

# Markdown
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true